# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaflet_storage', '0003_auto_20160910_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='tilelayer',
            name='tms',
            field=models.BooleanField(default=False),
        ),
    ]
